from turtle import *

def draw_calculator():
    speed('fastest')
    penup()
    seth(180)
    fd(150)
    left(90)
    fd(200)
    seth(0)
    pendown()
    fd(300)
    left(90)
    fd(450)
    left(90)
    fd(300)
    left(90)
    fd(450)
    seth(0)
    fd(75)
    left(90)
    fd(300)
    left(90)
    fd(75)
    seth(0)
    fd(150)
    right(90)
    fd(300)
    seth(90)
    fd(300)
    right(90)
    fd(75)
    right(90)
    fd(300)
    seth(90)
    fd(300)
    right(90)
    fd(75)
    right(90)
    fd(50)
    right(90)
    fd(300)
    left(90)
    fd(50)
    left(90)
    fd(300)
    right(90)
    fd(50)
    right(90)
    fd(300)
    left(90)
    fd(50)
    left(90)
    fd(300)
    right(90)
    fd(50)
    right(90)
    fd(300)
    left(90)
    fd(35)
    left(90)
    penup()
    fd(37.5)
    write("+/-", True, align="center", font=8)
    fd(60)
    write("0", True, align="center", font=8)
    fd(72)
    write(".", True, align="center", font=8)
    fd(70)
    write("=", True, align="center", font=8)
    left(90)
    fd(50)
    seth(180)
    fd(5)
    write("+", True, align="center", font=8)
    fd(80)
    write("3", True, align="center", font=8)
    fd(80)
    write("2", True, align="center", font=8)
    fd(78)
    write("1", True, align="center", font=8)
    fd(6.5)
    right(90)
    fd(50)
    write("4", True, align="center", font=8)
    right(90)
    fd(70)
    write("5", True, align="center", font=8)
    fd(70)
    write("6", True, align="center", font=8)
    fd(70)
    write("-", True, align="center", font=8)
    left(90)
    fd(50)
    left(90)
    fd(5)
    write("×", True, align="center", font=8)
    fd(82.5)
    write("9", True, align="center", font=8)
    fd(80)
    write("8", True, align="center", font=8)
    fd(80)
    write("7", True, align="center", font=8)
    right(90)
    fd(50)
    right(90)
    backward(5)
    write("⅟ₓ", True, align="center", font=8)
    fd(70)
    write("ₓ²", True, align="center", font=8)
    fd(67.5)
    write("²√ₓ", True, align="center", font=8)
    fd(64)
    write("÷", True, align="center", font=8)
    left(90)
    fd(50)
    left(90)
    fd(6)
    write("←", True, align="center", font=8)
    fd(85)
    write("C", True, align="center", font=8)
    fd(82)
    write("CE", True, align="center", font=8)
    fd(86)
    write("%", True, align="center", font=8)
    fd(10)
    right(90)
    fd(60)
    isvisible()


def play(message, count):
    print(message)
    def call(x, y):
        print(x, y)
        if x <= 0 and x >= -75 and y <= -150 and y >= -200:
            write("0 ", True, align="left", font=8)
            play(message+"0", count+1)
        elif x <=75 and x >=0 and y <= -150 and y >= -200:
            write(". ", True, align="left", font=8)
            play(message+".", count+1)
        elif x <= 150 and x >= 75 and y <= -150 and y >= -200:
            result = ""
            try:
                result = str(eval(message))
            except:
                result = "Error"
            write("= ", True, align="left", font=8)
            write(result, True, align="left", font=8)
            if result == "Error":
                result = ""
            play(result, count + 1)
        elif x <= -75 and x >= -150 and y <= -100 and y >= -150:
            write("1 ", True, align="left", font=8)
            play(message + "1", count+1)
        elif x <= 0 and x >= -75 and y <= -100 and y >= -150:
            write("2 ", True, align="left", font=8)
            play(message + "2", count+1)
        elif x <= 75 and x >= 0 and y <= -100 and y >= -150:
            write("3 ", True, align="left", font=8)
            play(message + "3", count+1)
        elif x <= 150 and x >= 75 and y <= -100 and y >= -150:
            write("+ ", True, align="left", font=8)
            play(message + "+", count+1)
        elif x <= -75 and x >= -150 and y <= -50 and y >= -100:
            write("4 ", True, align="left", font=8)
            play(message + "4", count+1)
        elif x <= 0 and x >= -75 and y <= -50 and y >= -100:
            write("5 ", True, align="left", font=8)
            play(message + "5", count+1)
        elif x <= 75 and x >= 0 and y <= -50 and y >= -100:
            write("6 ", True, align="left", font=8)
            play(message + "6", count+1)
        elif x <= 150 and x >= 75 and y <= -50 and y >= -100:
            write("- ", True, align="left", font=8)
            play(message + "-", count+1)
        elif x <= -75 and x >= -150 and y <= 0 and y >= -50:
            write("7 ", True, align="left", font=8)
            play(message + "7", count+1)
        elif x <= 0 and x >= -75 and y <= 0 and y >= -50:
            write("8 ", True, align="left", font=8)
            play(message + "8", count+1)
        elif x <= 75 and x >= 0 and y <= 0 and y >= -50:
            write("9 ", True, align="left", font=8)
            play(message + "9", count+1)
        elif x <= 150 and x >= 75 and y <= 0 and y >= -50:
            write("× ", True, align="left", font=8)
            play(message + "*", count+1)
        elif x <= 150 and x >= 75 and y <= 50 and y >= 0:
            write("÷ ", True, align="left", font=8)
            play(message + "/", count+1)
        elif x <= 75 and x >= -75 and y <= 100 and y >= 50:
            play("", 0)
            reset()
            draw_calculator()
        elif x <= 150 and x >= 75 and y <= 100 and y >= 50:
            b=len(message)-1
            if count > 0:
                play(message[0:b], count-1)
                undo()
            print(b)
        else:
            play(message, count)

    onscreenclick(call)


draw_calculator()
play("", 0)

done()
